spring.application.name=shortneer

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/springdata1}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.data.redis.url=${REDIS_URL:redis://localhost:6379}

server.port=${PORT:8080}
server.address=0.0.0.0

admin.default-password=${ADMIN_PASSWORD}

jwt.secret=${JWT_SECRET}